CREATE TABLE player (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  alias TEXT NOT NULL,
  win INTEGER NOT NULL,
  loss INTEGER NOT NULL
);

CREATE TABLE deck (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  alias TEXT NOT NULL,
  player_id INTEGER NOT NULL
);